In [57]:
import pandas as pd
import numpy as np

df = pd.DataFrame({

    "Customer_ID": [
        1001, "ID1002", None, 1004,
        -1005, 1006, "one007", 1008,
        1009, 1010, "??", 1012,
        1013, None, 1015, "cust16",
        1017, 1018, 1018, "XYZ"
    ],

    "Name": [
        "John", "", None, "Mary",
        "KOFI", "esi", "123",
        "Akos@", "Nana", "Kwame",
        "Abena", "Kojo2", "Linda##",
        "Michael", "Sarah", "Daniel",
        " ", "Paul", "Paul", "Unknown123"
    ],

    "Age": [
        25, "thirty", None, -5,
        200, "26yrs", "??",
        27, "old", 24,
        0, "twenty one", 26,
        None, 999, 23,
        "NaN", 28, 28, "unknown"
    ],

    "Gender": [
        "M", "F", "Male", "female",
        "m", None, "Unknown",
        "X", "Boy", "Girl",
        "", "FEMALE", "Male123",
        "M", "f", "N/A",
        "Female", "M", "M", "??"
    ],

    "City": [
        "Accra", "Kumasi", None, "123",
        "ACCRA", "accra", "Ksi",
        "Tamale", "Tema", "Tema",
        "Unknown", "", "Kum@si",
        "TEMA", "Kumasi", "Acc",
        "Village", "NULL", "Tema", "??"
    ],

    "Salary": [
        5000, "7000gh", None, -100,
        9999999, "five thousand", 6200,
        0, "???", 5300,
        "NaN", 4700, 999999999,
        None, "6100", "salary",
        6400, 5000, 5000, ""
    ],

    "Loan_Status": [
        "Approved", "Rejected", None, "APPROVED",
        "approved", "Yes", "No",
        "Pending", "Rejected", "",
        "unknown", "approved", "APPROVE",
        "Reject", "A", "R",
        None, "Approved", "Approved", "???"
    ],

    "Year": [
        2026, "2025", None, 1999,
        3000, "two thousand",
        2024, -1, 2023,
        "", "future", 2025,
        2024, 2035, None,
        2010, "unknown", 2026,
        2026, "??"
    ],

    "Credit_Score": [
        700, None, -50, 1200,
        "bad", 710, 640,
        "", 660, "excellent",
        715, 0, 680,
        None, 9999, "low",
        710, 700, 700, "???"
    ],

    "Account_Balance": [
        1200, -500, None, "unknown",
        300, 99999999, "",
        400, -1000, 750,
        "NaN", 600, 1000,
        None, "1250", "balance",
        950, 1150, 1150, "???"
    ],

    "Transactions": [
        12, -5, None, "many",
        3, 999, "18x",
        "", 6, 14,
        16, 0, -1,
        "two", 13, None,
        9999, 17, 17, "???"
    ],

    "Device_Type": [
        "Android", "iOS", None, "ANDROID",
        "android", "Blackberry",
        "Symbian", "", "Tablet",
        "iPhone", "Nokia",
        "Android123", "IOS",
        "PC", "Laptop", "unknown",
        "Android", "Android", None, "???"
    ],

    "Employment": [
        "Employed", None, "Self",
        "Jobless", "Retired",
        "employed", "", "N/A",
        "Unemployed", "Worker",
        "Self-employed", "EMPLOYED",
        "none", "Unknown", "Self",
        "Retired", "??", "Employed",
        "Employed", ""
    ],

    "Marital_Status": [
        "Single", None, "Married",
        "Complicated", "single",
        "", "Unknown",
        "Divorced", "Widowed",
        "MARRIED", "??",
        "Single123", "Marry",
        None, "Single", "Taken",
        "Complicated", "", "Single", "N/A"
    ],

    "Education": [
        "Degree", None, "Diploma",
        "Masters", "PhD",
        "degree", "", "??",
        "None", "Diploma123",
        "Basic", "Unknown",
        "SHS", "Dropout",
        "Certificate", None,
        "Degree", "degree",
        "Masters", "N/A"
    ],

    "Loan_Amount": [
        1000, None, -500, "ten thousand",
        999999, "", 1800,
        "loan", 2200, 1600,
        "NaN", 0, -1400,
        None, "2300", "???",
        1900, 2600, 2600, "unknown"
    ],

    "Interest_Rate": [
        10, None, -3, 200,
        "high", "", 13,
        "low", 0, 9,
        "11%", 16, -1,
        17, None, "rate",
        9, 11, 11, "???"
    ],

    "Region": [
        "Greater Accra", None, "Ashanti",
        "Northern", "", "unknown",
        "GA", "123", "Volta",
        "Ashanti", "??",
        "Western", "Eastern",
        None, "Upper East",
        "Upper West", "Savannah",
        "Greater Accra", "", "N/A"
    ],

    "Has_Defaulted": [
        0, 1, None, "Yes",
        "No", "", -1,
        2, "defaulted", 0,
        "unknown", 1, 0,
        None, "True", "False",
        "??", 0, 0, ""
    ],

    "Online_User": [
        1, 0, None, "sometimes",
        "Yes", "", -1,
        2, "online", 1,
        "offline", 0, 1,
        None, "True", "False",
        "??", 1, 1, ""
    ],

    "Last_Login_Days": [
        1, None, -2, 800,
        "yesterday", "", 7,
        "never", 0, 2,
        "many", 9, -10,
        None, 3650, "today",
        8, 1, 1, "???"
    ]

})

print(df)

   Customer_ID        Name         Age   Gender     City         Salary  \
0         1001        John          25        M    Accra           5000
1       ID1002                  thirty        F   Kumasi         7000gh
2         None         NaN        None     Male      NaN           None
3         1004        Mary          -5   female      123           -100
4        -1005        KOFI         200        m    ACCRA        9999999
5         1006         esi       26yrs      NaN    accra  five thousand
6       one007         123          ??  Unknown      Ksi           6200
7         1008       Akos@          27        X   Tamale              0
8         1009        Nana         old      Boy     Tema            ???
9         1010       Kwame          24     Girl     Tema           5300
10          ??       Abena           0           Unknown            NaN
11        1012       Kojo2  twenty one   FEMALE                    4700
12        1013     Linda##          26  Male123   Kum@si      999999999
13        None     Michael        None        M     TEMA           None
14        1015       Sarah         999        f   Kumasi           6100
15      cust16      Daniel          23      N/A      Acc         salary
16        1017                     NaN   Female  Village           6400
17        1018        Paul          28        M     NULL           5000
18        1018        Paul          28        M     Tema           5000
19         XYZ  Unknown123     unknown       ??       ??

   Loan_Status          Year Credit_Score Account_Balance  ... Device_Type  \
0     Approved          2026          700            1200  ...     Android
1     Rejected          2025         None            -500  ...         iOS
2          NaN          None          -50            None  ...         NaN
3     APPROVED          1999         1200         unknown  ...     ANDROID
4     approved          3000          bad             300  ...     android
5          Yes  two thousand          710        99999999  ...  Blackberry
6           No          2024          640                  ...     Symbian
7      Pending            -1                          400  ...
8     Rejected          2023          660           -1000  ...      Tablet
9                               excellent             750  ...      iPhone
10     unknown        future          715             NaN  ...       Nokia
11    approved          2025            0             600  ...  Android123
12     APPROVE          2024          680            1000  ...         IOS
13      Reject          2035         None            None  ...          PC
14           A          None         9999            1250  ...      Laptop
15           R          2010          low         balance  ...     unknown
16         NaN       unknown          710             950  ...     Android
17    Approved          2026          700            1150  ...     Android
18    Approved          2026          700            1150  ...         NaN
19         ???            ??          ???             ???  ...         ???

       Employment Marital_Status    Education   Loan_Amount Interest_Rate  \
0        Employed         Single       Degree          1000            10
1             NaN            NaN          NaN          None          None
2            Self        Married      Diploma          -500            -3
3         Jobless    Complicated      Masters  ten thousand           200
4         Retired         single          PhD        999999          high
5        employed                      degree
6                        Unknown                       1800            13
7             N/A       Divorced           ??          loan           low
8      Unemployed        Widowed         None          2200             0
9          Worker        MARRIED   Diploma123          1600             9
10  Self-employed             ??        Basic           NaN           11%
11       EMPLOYED      Single123      Unknown             0            16
12           none          Marry          SHS         -1400            -1
13        Unknown            NaN      Dropout          None            17
14           Self         Single  Certificate          2300          None
15        Retired          Taken          NaN           ???          rate
16             ??    Complicated       Degree          1900             9
17       Employed                      degree          2600            11
18       Employed         Single      Masters          2600            11
19                           N/A          N/A       unknown           ???

           Region Has_Defaulted Online_User Last_Login_Days
0   Greater Accra             0           1               1
1             NaN             1           0            None
2         Ashanti          None        None              -2
3        Northern           Yes   sometimes             800
4                            No         Yes       yesterday
5         unknown
6              GA            -1          -1               7
7             123             2           2           never
8           Volta     defaulted      online               0
9         Ashanti             0           1               2
10             ??       unknown     offline            many
11        Western             1           0               9
12        Eastern             0           1             -10
13            NaN          None        None            None
14     Upper East          True        True            3650
15     Upper West         False       False           today
16       Savannah            ??          ??               8
17  Greater Accra             0           1               1
18                            0           1               1
19            N/A                                       ???

[20 rows x 21 columns]

In [62]:
df.info()

<class 'pandas.DataFrame'>
Index: 18 entries, 0 to 19
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Customer_ID      18 non-null     object
 1   Name             18 non-null     object
 2   Age              18 non-null     object
 3   Gender           18 non-null     object
 4   City             18 non-null     object
 5   Salary           18 non-null     object
 6   Loan_Status      18 non-null     object
 7   Year             18 non-null     object
 8   Credit_Score     18 non-null     object
 9   Account_Balance  18 non-null     object
 10  Transactions     18 non-null     object
 11  Device_Type      18 non-null     object
 12  Employment       18 non-null     object
 13  Marital_Status   18 non-null     object
 14  Education        18 non-null     object
 15  Loan_Amount      18 non-null     object
 16  Interest_Rate    18 non-null     object
 17  Region           18 non-null     object
 18  Has_Defaulted    18 non-null     object
 19  Online_User      18 non-null     object
 20  Last_Login_Days  18 non-null     object
dtypes: object(21)
memory usage: 3.1+ KB

In [63]:
print(df.isnull().sum())

Customer_ID        0
Name               0
Age                0
Gender             0
City               0
Salary             0
Loan_Status        0
Year               0
Credit_Score       0
Account_Balance    0
Transactions       0
Device_Type        0
Employment         0
Marital_Status     0
Education          0
Loan_Amount        0
Interest_Rate      0
Region             0
Has_Defaulted      0
Online_User        0
Last_Login_Days    0
dtype: int64

In [66]:
df["Name"] = df["Name"].str.strip()
df

,Customer_ID,Name,Age,Gender,City,Salary,Loan_Status,Year,Credit_Score,Account_Balance,...,Device_Type,Employment,Marital_Status,Education,Loan_Amount,Interest_Rate,Region,Has_Defaulted,Online_User,Last_Login_Days
0,1001,John,25,M,Accra,5000,Approved,2026,700,1200,...,Android,Employed,Single,Degree,1000,10,Greater Accra,0,1,1
1,ID1002,,thirty,F,Kumasi,7000gh,Rejected,2025,0,-500,...,iOS,0,0,0,0,0,0,1,0,0
2,0,NaN,0,Male,0,0,0,0,-50,0,...,0,Self,Married,Diploma,-500,-3,Ashanti,0,0,-2
3,1004,Mary,-5,female,123,-100,APPROVED,1999,1200,unknown,...,ANDROID,Jobless,Complicated,Masters,ten thousand,200,Northern,Yes,sometimes,800
4,-1005,KOFI,200,m,ACCRA,9999999,approved,3000,bad,300,...,android,Retired,single,PhD,999999,high,,No,Yes,yesterday
5,1006,esi,26yrs,0,accra,five thousand,Yes,two thousand,710,99999999,...,Blackberry,employed,,degree,,,unknown,,,
6,one007,123,??,Unknown,Ksi,6200,No,2024,640,,...,Symbian,,Unknown,,1800,13,GA,-1,-1,7
7,1008,Akos@,27,X,Tamale,0,Pending,-1,,400,...,,N/A,Divorced,??,loan,low,123,2,2,never
8,1009,Nana,old,Boy,Tema,???,Rejected,2023,660,-1000,...,Tablet,Unemployed,Widowed,None,2200,0,Volta,defaulted,online,0
9,1010,Kwame,24,Girl,Tema,5300,,,excellent,750,...,iPhone,Worker,MARRIED,Diploma123,1600,9,Ashanti,0,1,2
10,??,Abena,0,,Unknown,NaN,unknown,future,715,NaN,...,Nokia,Self-employed,??,Basic,NaN,11%,??,unknown,offline,many
11,1012,Kojo2,twenty one,FEMALE,,4700,approved,2025,0,600,...,Android123,EMPLOYED,Single123,Unknown,0,16,Western,1,0,9
12,1013,Linda##,26,Male123,Kum@si,999999999,APPROVE,2024,680,1000,...,IOS,none,Marry,SHS,-1400,-1,Eastern,0,1,-10
13,0,Michael,0,M,TEMA,0,Reject,2035,0,0,...,PC,Unknown,0,Dropout,0,17,0,0,0,0
14,1015,Sarah,999,f,Kumasi,6100,A,0,9999,1250,...,Laptop,Self,Single,Certificate,2300,0,Upper East,True,True,3650
16,1017,,NaN,Female,Village,6400,0,unknown,710,950,...,Android,??,Complicated,Degree,1900,9,Savannah,??,??,8
17,1018,Paul,28,M,NULL,5000,Approved,2026,700,1150,...,Android,Employed,,degree,2600,11,Greater Accra,0,1,1
19,XYZ,Unknown123,unknown,??,??,,???,??,???,???,...,???,,N/A,N/A,unknown,???,N/A,,,???

In [67]:
# Remove duplicates
df = df.drop_duplicates(subset="Transactions")
print(df)

   Customer_ID        Name      Age   Gender     City         Salary  \
0         1001        John       25        M    Accra           5000
1       ID1002               thirty        F   Kumasi         7000gh
2            0         NaN        0     Male        0              0
3         1004        Mary       -5   female      123           -100
4        -1005        KOFI      200        m    ACCRA        9999999
5         1006         esi    26yrs        0    accra  five thousand
6       one007         123       ??  Unknown      Ksi           6200
7         1008       Akos@       27        X   Tamale              0
8         1009        Nana      old      Boy     Tema            ???
9         1010       Kwame       24     Girl     Tema           5300
10          ??       Abena        0           Unknown            NaN
12        1013     Linda##       26  Male123   Kum@si      999999999
13           0     Michael        0        M     TEMA              0
14        1015       Sarah      999        f   Kumasi           6100
16        1017                  NaN   Female  Village           6400
17        1018        Paul       28        M     NULL           5000
19         XYZ  Unknown123  unknown       ??       ??

   Loan_Status          Year Credit_Score Account_Balance  ... Device_Type  \
0     Approved          2026          700            1200  ...     Android
1     Rejected          2025            0            -500  ...         iOS
2            0             0          -50               0  ...           0
3     APPROVED          1999         1200         unknown  ...     ANDROID
4     approved          3000          bad             300  ...     android
5          Yes  two thousand          710        99999999  ...  Blackberry
6           No          2024          640                  ...     Symbian
7      Pending            -1                          400  ...
8     Rejected          2023          660           -1000  ...      Tablet
9                               excellent             750  ...      iPhone
10     unknown        future          715             NaN  ...       Nokia
12     APPROVE          2024          680            1000  ...         IOS
13      Reject          2035            0               0  ...          PC
14           A             0         9999            1250  ...      Laptop
16           0       unknown          710             950  ...     Android
17    Approved          2026          700            1150  ...     Android
19         ???            ??          ???             ???  ...         ???

       Employment Marital_Status    Education   Loan_Amount Interest_Rate  \
0        Employed         Single       Degree          1000            10
1               0              0            0             0             0
2            Self        Married      Diploma          -500            -3
3         Jobless    Complicated      Masters  ten thousand           200
4         Retired         single          PhD        999999          high
5        employed                      degree
6                        Unknown                       1800            13
7             N/A       Divorced           ??          loan           low
8      Unemployed        Widowed         None          2200             0
9          Worker        MARRIED   Diploma123          1600             9
10  Self-employed             ??        Basic           NaN           11%
12           none          Marry          SHS         -1400            -1
13        Unknown              0      Dropout             0            17
14           Self         Single  Certificate          2300             0
16             ??    Complicated       Degree          1900             9
17       Employed                      degree          2600            11
19                           N/A          N/A       unknown           ???

           Region Has_Defaulted Online_User Last_Login_Days
0   Greater Accra             0           1               1
1               0             1           0               0
2         Ashanti             0           0              -2
3        Northern           Yes   sometimes             800
4                            No         Yes       yesterday
5         unknown
6              GA            -1          -1               7
7             123             2           2           never
8           Volta     defaulted      online               0
9         Ashanti             0           1               2
10             ??       unknown     offline            many
12        Eastern             0           1             -10
13              0             0           0               0
14     Upper East          True        True            3650
16       Savannah            ??          ??               8
17  Greater Accra             0           1               1
19            N/A                                       ???

[17 rows x 21 columns]

In [60]:
# Fill missing values
df = df.fillna(0)
df

,Customer_ID,Name,Age,Gender,City,Salary,Loan_Status,Year,Credit_Score,Account_Balance,...,Device_Type,Employment,Marital_Status,Education,Loan_Amount,Interest_Rate,Region,Has_Defaulted,Online_User,Last_Login_Days
0,1001,John,25,M,Accra,5000,Approved,2026,700,1200,...,Android,Employed,Single,Degree,1000,10,Greater Accra,0,1,1
1,ID1002,,thirty,F,Kumasi,7000gh,Rejected,2025,0,-500,...,iOS,0,0,0,0,0,0,1,0,0
2,0,0,0,Male,0,0,0,0,-50,0,...,0,Self,Married,Diploma,-500,-3,Ashanti,0,0,-2
3,1004,Mary,-5,female,123,-100,APPROVED,1999,1200,unknown,...,ANDROID,Jobless,Complicated,Masters,ten thousand,200,Northern,Yes,sometimes,800
4,-1005,KOFI,200,m,ACCRA,9999999,approved,3000,bad,300,...,android,Retired,single,PhD,999999,high,,No,Yes,yesterday
5,1006,esi,26yrs,0,accra,five thousand,Yes,two thousand,710,99999999,...,Blackberry,employed,,degree,,,unknown,,,
6,one007,123,??,Unknown,Ksi,6200,No,2024,640,,...,Symbian,,Unknown,,1800,13,GA,-1,-1,7
7,1008,Akos@,27,X,Tamale,0,Pending,-1,,400,...,,N/A,Divorced,??,loan,low,123,2,2,never
8,1009,Nana,old,Boy,Tema,???,Rejected,2023,660,-1000,...,Tablet,Unemployed,Widowed,None,2200,0,Volta,defaulted,online,0
9,1010,Kwame,24,Girl,Tema,5300,,,excellent,750,...,iPhone,Worker,MARRIED,Diploma123,1600,9,Ashanti,0,1,2
10,??,Abena,0,,Unknown,NaN,unknown,future,715,NaN,...,Nokia,Self-employed,??,Basic,NaN,11%,??,unknown,offline,many
11,1012,Kojo2,twenty one,FEMALE,,4700,approved,2025,0,600,...,Android123,EMPLOYED,Single123,Unknown,0,16,Western,1,0,9
12,1013,Linda##,26,Male123,Kum@si,999999999,APPROVE,2024,680,1000,...,IOS,none,Marry,SHS,-1400,-1,Eastern,0,1,-10
13,0,Michael,0,M,TEMA,0,Reject,2035,0,0,...,PC,Unknown,0,Dropout,0,17,0,0,0,0
14,1015,Sarah,999,f,Kumasi,6100,A,0,9999,1250,...,Laptop,Self,Single,Certificate,2300,0,Upper East,True,True,3650
16,1017,,NaN,Female,Village,6400,0,unknown,710,950,...,Android,??,Complicated,Degree,1900,9,Savannah,??,??,8
17,1018,Paul,28,M,NULL,5000,Approved,2026,700,1150,...,Android,Employed,,degree,2600,11,Greater Accra,0,1,1
19,XYZ,Unknown123,unknown,??,??,,???,??,???,???,...,???,,N/A,N/A,unknown,???,N/A,,,???

In [54]:
import pandas as pd
import numpy as np

# 1. Replace messy values
df.replace(["??", "unknown", "N/A", "", "NULL"], np.nan, inplace=True)

# 2. Convert to correct datatypes
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Salary"] = pd.to_numeric(df["Salary"], errors="coerce")

# 3. Remove duplicates
df = df.drop_duplicates()

# 4. Fill missing values
df = df.fillna(0)

print(df)

   Customer_ID        Name    Age   Gender     City       Salary Loan_Status  \
0         1001        John   25.0        M    Accra       5000.0    Approved
1       ID1002           0    0.0        F   Kumasi          0.0    Rejected
2            0           0    0.0     Male        0          0.0           0
3         1004        Mary   -5.0   female      123       -100.0    APPROVED
4        -1005        KOFI  200.0        m    ACCRA    9999999.0    approved
5         1006         esi    0.0        0    accra          0.0         Yes
6       one007         123    0.0  Unknown      Ksi       6200.0          No
7         1008       Akos@   27.0        X   Tamale          0.0     Pending
8         1009        Nana    0.0      Boy     Tema          0.0    Rejected
9         1010       Kwame   24.0     Girl     Tema       5300.0           0
10           0       Abena    0.0        0  Unknown          0.0           0
11        1012       Kojo2    0.0   FEMALE        0       4700.0    approved
12        1013     Linda##   26.0  Male123   Kum@si  999999999.0     APPROVE
13           0     Michael    0.0        M     TEMA          0.0      Reject
14        1015       Sarah  999.0        f   Kumasi       6100.0           A
16        1017                0.0   Female  Village       6400.0           0
17        1018        Paul   28.0        M        0       5000.0    Approved
19         XYZ  Unknown123    0.0        0        0          0.0         ???

            Year Credit_Score Account_Balance  ... Device_Type     Employment  \
0           2026          700            1200  ...     Android       Employed
1           2025            0            -500  ...         iOS              0
2              0          -50               0  ...           0           Self
3           1999         1200               0  ...     ANDROID        Jobless
4           3000          bad             300  ...     android        Retired
5   two thousand          710        99999999  ...  Blackberry       employed
6           2024          640               0  ...     Symbian              0
7             -1            0             400  ...           0              0
8           2023          660           -1000  ...      Tablet     Unemployed
9              0    excellent             750  ...      iPhone         Worker
10        future          715             NaN  ...       Nokia  Self-employed
11          2025            0             600  ...  Android123       EMPLOYED
12          2024          680            1000  ...         IOS           none
13          2035            0               0  ...          PC        Unknown
14             0         9999            1250  ...      Laptop           Self
16             0          710             950  ...     Android              0
17          2026          700            1150  ...     Android       Employed
19             0          ???             ???  ...         ???              0

   Marital_Status    Education   Loan_Amount Interest_Rate         Region  \
0          Single       Degree          1000            10  Greater Accra
1               0            0             0             0              0
2         Married      Diploma          -500            -3        Ashanti
3     Complicated      Masters  ten thousand           200       Northern
4          single          PhD        999999          high              0
5               0       degree             0             0              0
6         Unknown            0          1800            13             GA
7        Divorced            0          loan           low            123
8         Widowed         None          2200             0          Volta
9         MARRIED   Diploma123          1600             9        Ashanti
10              0        Basic           NaN           11%              0
11      Single123      Unknown             0            16        Western
12          Marry          SHS         -1400            -1        Eastern
13              0      Dropout             0            17              0
14         Single  Certificate          2300             0     Upper East
16    Complicated       Degree          1900             9       Savannah
17              0       degree          2600            11  Greater Accra
19              0            0             0           ???              0

   Has_Defaulted Online_User Last_Login_Days
0              0           1               1
1              1           0               0
2              0           0              -2
3            Yes   sometimes             800
4             No         Yes       yesterday
5              0           0               0
6             -1          -1               7
7              2           2           never
8      defaulted      online               0
9              0           1               2
10             0     offline            many
11             1           0               9
12             0           1             -10
13             0           0               0
14          True        True            3650
16             0           0               8
17             0           1               1
19             0           0             ???

[18 rows x 21 columns]

In [55]:
df

,Customer_ID,Name,Age,Gender,City,Salary,Loan_Status,Year,Credit_Score,Account_Balance,...,Device_Type,Employment,Marital_Status,Education,Loan_Amount,Interest_Rate,Region,Has_Defaulted,Online_User,Last_Login_Days
0,1001,John,25.0,M,Accra,5000.0,Approved,2026,700,1200,...,Android,Employed,Single,Degree,1000,10,Greater Accra,0,1,1
1,ID1002,0,0.0,F,Kumasi,0.0,Rejected,2025,0,-500,...,iOS,0,0,0,0,0,0,1,0,0
2,0,0,0.0,Male,0,0.0,0,0,-50,0,...,0,Self,Married,Diploma,-500,-3,Ashanti,0,0,-2
3,1004,Mary,-5.0,female,123,-100.0,APPROVED,1999,1200,0,...,ANDROID,Jobless,Complicated,Masters,ten thousand,200,Northern,Yes,sometimes,800
4,-1005,KOFI,200.0,m,ACCRA,9999999.0,approved,3000,bad,300,...,android,Retired,single,PhD,999999,high,0,No,Yes,yesterday
5,1006,esi,0.0,0,accra,0.0,Yes,two thousand,710,99999999,...,Blackberry,employed,0,degree,0,0,0,0,0,0
6,one007,123,0.0,Unknown,Ksi,6200.0,No,2024,640,0,...,Symbian,0,Unknown,0,1800,13,GA,-1,-1,7
7,1008,Akos@,27.0,X,Tamale,0.0,Pending,-1,0,400,...,0,0,Divorced,0,loan,low,123,2,2,never
8,1009,Nana,0.0,Boy,Tema,0.0,Rejected,2023,660,-1000,...,Tablet,Unemployed,Widowed,None,2200,0,Volta,defaulted,online,0
9,1010,Kwame,24.0,Girl,Tema,5300.0,0,0,excellent,750,...,iPhone,Worker,MARRIED,Diploma123,1600,9,Ashanti,0,1,2
10,0,Abena,0.0,0,Unknown,0.0,0,future,715,NaN,...,Nokia,Self-employed,0,Basic,NaN,11%,0,0,offline,many
11,1012,Kojo2,0.0,FEMALE,0,4700.0,approved,2025,0,600,...,Android123,EMPLOYED,Single123,Unknown,0,16,Western,1,0,9
12,1013,Linda##,26.0,Male123,Kum@si,999999999.0,APPROVE,2024,680,1000,...,IOS,none,Marry,SHS,-1400,-1,Eastern,0,1,-10
13,0,Michael,0.0,M,TEMA,0.0,Reject,2035,0,0,...,PC,Unknown,0,Dropout,0,17,0,0,0,0
14,1015,Sarah,999.0,f,Kumasi,6100.0,A,0,9999,1250,...,Laptop,Self,Single,Certificate,2300,0,Upper East,True,True,3650
16,1017,,0.0,Female,Village,6400.0,0,0,710,950,...,Android,0,Complicated,Degree,1900,9,Savannah,0,0,8
17,1018,Paul,28.0,M,0,5000.0,Approved,2026,700,1150,...,Android,Employed,0,degree,2600,11,Greater Accra,0,1,1
19,XYZ,Unknown123,0.0,0,0,0.0,???,0,???,???,...,???,0,0,0,0,???,0,0,0,???