In [1]:
import pandas as pd

df = pd.read_csv("orders.csv")
print(df)

    OrderID      CustomerName                Product     Category  Quantity  \
0      1001        John Smith                 Laptop  Electronics         1
1      1002         Sarah Lee             Headphones  Electronics         2
2      1003          Ali Khan           Office Chair    Furniture         1
3      1004        Alice Wong              Desk Lamp    Furniture         3
4      1005     Carlos Mendez               Keyboard  Electronics         2
5      1006      Nora Ibrahim               Notebook   Stationery         5
6      1007       Emily Davis          Standing Desk    Furniture         1
7      1008        James Park                Monitor  Electronics         2
8      1009       Maria Rossi                    Pen   Stationery        10
9      1010  Takeshi Nakamura                  Mouse  Electronics         1
10     1011     Sophie Martin                 Webcam  Electronics         1
11     1012         Raj Patel           File Cabinet    Furniture         2
12     1013       Emma Wilson                Stapler   Stationery         3
13     1014   Diego Rodriguez              USB Drive  Electronics         5
14     1015         Lisa Chen              Bookshelf    Furniture         1
15     1016      Ahmed Hassan          Printer Paper   Stationery        20
16     1017     Anna Kowalski         Wireless Mouse  Electronics         2
17     1018     Michael Brown         Desk Organizer    Furniture         1
18     1019       Yuki Tanaka             Calculator  Electronics         1
19     1020   Fatima Al-Zahra             Whiteboard    Furniture         1
20     1021    David Thompson           Highlighters   Stationery         8
21     1022    Isabella Silva      Bluetooth Speaker  Electronics         1
22     1023    Oliver Schmidt           Office Plant    Furniture         2
23     1024        Zara Ahmed           Sticky Notes   Stationery        15
24     1025    Lucas Anderson           Tablet Stand  Electronics         1
25     1026      Chloe Dubois         Paper Shredder  Electronics         1
26     1027     Miguel Torres         Desk Chair Mat    Furniture         1
27     1028       Nina Petrov           Binder Clips   Stationery        12
28     1029      Seo-yeon Kim      Wireless Keyboard  Electronics         1
29     1030   Giuseppe Romano          Desk Calendar    Furniture         1
30     1031      Amira Hassan                USB Hub  Electronics         1
31     1032     Thomas Müller       Document Scanner  Electronics         1
32     1033   Sofia Rodriguez  Desk Drawer Organizer    Furniture         1
33     1034      Alex Johnson            Index Cards   Stationery       100
34     1035     Yuki Yamamoto          Monitor Stand  Electronics         1
35     1036     Emma Thompson     Desk Lamp with USB    Furniture         1
36     1037     Carlos Santos       Wireless Earbuds  Electronics         1
37     1038    Leila Mansouri               Desk Pad    Furniture         1
38     1039        Daniel Kim            Power Strip  Electronics         2
39     1040      Anna Ivanova             Desk Clock    Furniture         1

     Price   OrderDate Shipped       Country
0   1200.0  2024-06-01     Yes           USA
1    150.0  2024-06-03      No        Canada
2    300.0  2024-06-04     Yes           UAE
3     45.0  2024-06-05     Yes     Singapore
4     80.0  2024-06-06      No        Mexico
5      5.0  2024-06-07     Yes           UAE
6    450.0  2024-06-08     Yes            UK
7    220.0  2024-06-09      No   South Korea
8      1.5  2024-06-10     Yes         Italy
9     35.0  2024-06-11     Yes         Japan
10    85.0  2024-06-12     Yes        France
11   180.0  2024-06-13      No         India
12    12.0  2024-06-14     Yes     Australia
13    25.0  2024-06-15     Yes         Spain
14   280.0  2024-06-16      No         China
15     8.0  2024-06-17     Yes         Egypt
16    45.0  2024-06-18     Yes        Poland
17    65.0  2024-06-19      No           USA
18    15.0  2024-06-20     Yes         Japan
19   120.0  2024-06-21     Yes  Saudi Arabia
20     3.5  2024-06-22      No        Canada
21    95.0  2024-06-23     Yes        Brazil
22    35.0  2024-06-24     Yes       Germany
23     4.0  2024-06-25      No      Pakistan
24    28.0  2024-06-26     Yes        Sweden
25    75.0  2024-06-27     Yes        France
26    22.0  2024-06-28      No     Argentina
27     2.5  2024-06-29     Yes        Russia
28   110.0  2024-06-30     Yes   South Korea
29    18.0  2024-07-01      No         Italy
30    32.0  2024-07-02     Yes       Morocco
31   140.0  2024-07-03     Yes       Germany
32    42.0  2024-07-04      No      Colombia
33     0.8  2024-07-05     Yes           USA
34    55.0  2024-07-06     Yes         Japan
35    68.0  2024-07-07      No            UK
36   125.0  2024-07-08     Yes      Portugal
37    28.0  2024-07-09     Yes          Iran
38    18.0  2024-07-10      No   South Korea
39    35.0  2024-07-11     Yes       Ukraine

In [2]:
df.head()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       40 non-null     int64
 1   CustomerName  40 non-null     str
 2   Product       40 non-null     str
 3   Category      40 non-null     str
 4   Quantity      40 non-null     int64
 5   Price         40 non-null     float64
 6   OrderDate     40 non-null     str
 7   Shipped       40 non-null     str
 8   Country       40 non-null     str
dtypes: float64(1), int64(2), str(6)
memory usage: 2.9 KB

In [4]:
df.tail()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [5]:
df.columns

Index(['OrderID', 'CustomerName', 'Product', 'Category', 'Quantity', 'Price',
       'OrderDate', 'Shipped', 'Country'],
      dtype='str')

In [6]:
df.describe

<bound method NDFrame.describe of     OrderID      CustomerName                Product     Category  Quantity  \
0      1001        John Smith                 Laptop  Electronics         1
1      1002         Sarah Lee             Headphones  Electronics         2
2      1003          Ali Khan           Office Chair    Furniture         1
3      1004        Alice Wong              Desk Lamp    Furniture         3
4      1005     Carlos Mendez               Keyboard  Electronics         2
5      1006      Nora Ibrahim               Notebook   Stationery         5
6      1007       Emily Davis          Standing Desk    Furniture         1
7      1008        James Park                Monitor  Electronics         2
8      1009       Maria Rossi                    Pen   Stationery        10
9      1010  Takeshi Nakamura                  Mouse  Electronics         1
10     1011     Sophie Martin                 Webcam  Electronics         1
11     1012         Raj Patel           File Cabinet    Furniture         2
12     1013       Emma Wilson                Stapler   Stationery         3
13     1014   Diego Rodriguez              USB Drive  Electronics         5
14     1015         Lisa Chen              Bookshelf    Furniture         1
15     1016      Ahmed Hassan          Printer Paper   Stationery        20
16     1017     Anna Kowalski         Wireless Mouse  Electronics         2
17     1018     Michael Brown         Desk Organizer    Furniture         1
18     1019       Yuki Tanaka             Calculator  Electronics         1
19     1020   Fatima Al-Zahra             Whiteboard    Furniture         1
20     1021    David Thompson           Highlighters   Stationery         8
21     1022    Isabella Silva      Bluetooth Speaker  Electronics         1
22     1023    Oliver Schmidt           Office Plant    Furniture         2
23     1024        Zara Ahmed           Sticky Notes   Stationery        15
24     1025    Lucas Anderson           Tablet Stand  Electronics         1
25     1026      Chloe Dubois         Paper Shredder  Electronics         1
26     1027     Miguel Torres         Desk Chair Mat    Furniture         1
27     1028       Nina Petrov           Binder Clips   Stationery        12
28     1029      Seo-yeon Kim      Wireless Keyboard  Electronics         1
29     1030   Giuseppe Romano          Desk Calendar    Furniture         1
30     1031      Amira Hassan                USB Hub  Electronics         1
31     1032     Thomas Müller       Document Scanner  Electronics         1
32     1033   Sofia Rodriguez  Desk Drawer Organizer    Furniture         1
33     1034      Alex Johnson            Index Cards   Stationery       100
34     1035     Yuki Yamamoto          Monitor Stand  Electronics         1
35     1036     Emma Thompson     Desk Lamp with USB    Furniture         1
36     1037     Carlos Santos       Wireless Earbuds  Electronics         1
37     1038    Leila Mansouri               Desk Pad    Furniture         1
38     1039        Daniel Kim            Power Strip  Electronics         2
39     1040      Anna Ivanova             Desk Clock    Furniture         1

     Price   OrderDate Shipped       Country
0   1200.0  2024-06-01     Yes           USA
1    150.0  2024-06-03      No        Canada
2    300.0  2024-06-04     Yes           UAE
3     45.0  2024-06-05     Yes     Singapore
4     80.0  2024-06-06      No        Mexico
5      5.0  2024-06-07     Yes           UAE
6    450.0  2024-06-08     Yes            UK
7    220.0  2024-06-09      No   South Korea
8      1.5  2024-06-10     Yes         Italy
9     35.0  2024-06-11     Yes         Japan
10    85.0  2024-06-12     Yes        France
11   180.0  2024-06-13      No         India
12    12.0  2024-06-14     Yes     Australia
13    25.0  2024-06-15     Yes         Spain
14   280.0  2024-06-16      No         China
15     8.0  2024-06-17     Yes         Egypt
16    45.0  2024-06-18     Yes        Poland
17    65.0  2024-06-19      No           USA
18    15.0  2024-06-20     Yes         Japan
19   120.0  2024-06-21     Yes  Saudi Arabia
20     3.5  2024-06-22      No        Canada
21    95.0  2024-06-23     Yes        Brazil
22    35.0  2024-06-24     Yes       Germany
23     4.0  2024-06-25      No      Pakistan
24    28.0  2024-06-26     Yes        Sweden
25    75.0  2024-06-27     Yes        France
26    22.0  2024-06-28      No     Argentina
27     2.5  2024-06-29     Yes        Russia
28   110.0  2024-06-30     Yes   South Korea
29    18.0  2024-07-01      No         Italy
30    32.0  2024-07-02     Yes       Morocco
31   140.0  2024-07-03     Yes       Germany
32    42.0  2024-07-04      No      Colombia
33     0.8  2024-07-05     Yes           USA
34    55.0  2024-07-06     Yes         Japan
35    68.0  2024-07-07      No            UK
36   125.0  2024-07-08     Yes      Portugal
37    28.0  2024-07-09     Yes          Iran
38    18.0  2024-07-10      No   South Korea
39    35.0  2024-07-11     Yes       Ukraine  >

In [7]:
df.index

RangeIndex(start=0, stop=40, step=1)

In [8]:
df["Category"]

0     Electronics
1     Electronics
2       Furniture
3       Furniture
4     Electronics
5      Stationery
6       Furniture
7     Electronics
8      Stationery
9     Electronics
10    Electronics
11      Furniture
12     Stationery
13    Electronics
14      Furniture
15     Stationery
16    Electronics
17      Furniture
18    Electronics
19      Furniture
20     Stationery
21    Electronics
22      Furniture
23     Stationery
24    Electronics
25    Electronics
26      Furniture
27     Stationery
28    Electronics
29      Furniture
30    Electronics
31    Electronics
32      Furniture
33     Stationery
34    Electronics
35      Furniture
36    Electronics
37      Furniture
38    Electronics
39      Furniture
Name: Category, dtype: str

In [10]:
df["Product"]

0                    Laptop
1                Headphones
2              Office Chair
3                 Desk Lamp
4                  Keyboard
5                  Notebook
6             Standing Desk
7                   Monitor
8                       Pen
9                     Mouse
10                   Webcam
11             File Cabinet
12                  Stapler
13                USB Drive
14                Bookshelf
15            Printer Paper
16           Wireless Mouse
17           Desk Organizer
18               Calculator
19               Whiteboard
20             Highlighters
21        Bluetooth Speaker
22             Office Plant
23             Sticky Notes
24             Tablet Stand
25           Paper Shredder
26           Desk Chair Mat
27             Binder Clips
28        Wireless Keyboard
29            Desk Calendar
30                  USB Hub
31         Document Scanner
32    Desk Drawer Organizer
33              Index Cards
34            Monitor Stand
35       Desk Lamp with USB
36         Wireless Earbuds
37                 Desk Pad
38              Power Strip
39               Desk Clock
Name: Product, dtype: str

In [11]:
df[["Product", "Category", "Country"]]

                  Product     Category       Country
0                  Laptop  Electronics           USA
1              Headphones  Electronics        Canada
2            Office Chair    Furniture           UAE
3               Desk Lamp    Furniture     Singapore
4                Keyboard  Electronics        Mexico
5                Notebook   Stationery           UAE
6           Standing Desk    Furniture            UK
7                 Monitor  Electronics   South Korea
8                     Pen   Stationery         Italy
9                   Mouse  Electronics         Japan
10                 Webcam  Electronics        France
11           File Cabinet    Furniture         India
12                Stapler   Stationery     Australia
13              USB Drive  Electronics         Spain
14              Bookshelf    Furniture         China
15          Printer Paper   Stationery         Egypt
16         Wireless Mouse  Electronics        Poland
17         Desk Organizer    Furniture           USA
18             Calculator  Electronics         Japan
19             Whiteboard    Furniture  Saudi Arabia
20           Highlighters   Stationery        Canada
21      Bluetooth Speaker  Electronics        Brazil
22           Office Plant    Furniture       Germany
23           Sticky Notes   Stationery      Pakistan
24           Tablet Stand  Electronics        Sweden
25         Paper Shredder  Electronics        France
26         Desk Chair Mat    Furniture     Argentina
27           Binder Clips   Stationery        Russia
28      Wireless Keyboard  Electronics   South Korea
29          Desk Calendar    Furniture         Italy
30                USB Hub  Electronics       Morocco
31       Document Scanner  Electronics       Germany
32  Desk Drawer Organizer    Furniture      Colombia
33            Index Cards   Stationery           USA
34          Monitor Stand  Electronics         Japan
35     Desk Lamp with USB    Furniture            UK
36       Wireless Earbuds  Electronics      Portugal
37               Desk Pad    Furniture          Iran
38            Power Strip  Electronics   South Korea
39             Desk Clock    Furniture       Ukraine

In [13]:
df.iloc[3]

OrderID               1004
CustomerName    Alice Wong
Product          Desk Lamp
Category         Furniture
Quantity                 3
Price                 45.0
OrderDate       2024-06-05
Shipped                Yes
Country          Singapore
Name: 3, dtype: object

In [20]:
df[df["Category"] == "Electronics"]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea

In [21]:
df.loc[df["Product"] == "Laptop"]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA

In [22]:
df.loc[df["Product"] == "Laptop"  , "CustomerName" ] = "Addo Emmanuel"

In [23]:
df.loc[df["Product"] == "Laptop"]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,Addo Emmanuel,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA

In [25]:
df.drop("CustomerName", axis=1, inplace=True)

In [26]:
df

,OrderID,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
5,1006,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
6,1007,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
8,1009,Pen,Stationery,10,1.5,2024-06-10,Yes,Italy
9,1010,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
10,1011,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
11,1012,File Cabinet,Furniture,2,180.0,2024-06-13,No,India
12,1013,Stapler,Stationery,3,12.0,2024-06-14,Yes,Australia
13,1014,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
14,1015,Bookshelf,Furniture,1,280.0,2024-06-16,No,China
15,1016,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
16,1017,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
17,1018,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
18,1019,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
19,1020,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,Saudi Arabia
20,1021,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
21,1022,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
22,1023,Office Plant,Furniture,2,35.0,2024-06-24,Yes,Germany
23,1024,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan
24,1025,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
25,1026,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
26,1027,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,Argentina
27,1028,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,Russia
28,1029,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
29,1030,Desk Calendar,Furniture,1,18.0,2024-07-01,No,Italy
30,1031,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
31,1032,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
32,1033,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,Colombia
33,1034,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
34,1035,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan
35,1036,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
38,1039,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea
39,1040,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [27]:
df.rename(columns={"OrderID" : "Order_ID"}, inplace= True)

In [28]:
df

,Order_ID,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
5,1006,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
6,1007,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
8,1009,Pen,Stationery,10,1.5,2024-06-10,Yes,Italy
9,1010,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
10,1011,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
11,1012,File Cabinet,Furniture,2,180.0,2024-06-13,No,India
12,1013,Stapler,Stationery,3,12.0,2024-06-14,Yes,Australia
13,1014,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
14,1015,Bookshelf,Furniture,1,280.0,2024-06-16,No,China
15,1016,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
16,1017,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
17,1018,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
18,1019,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
19,1020,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,Saudi Arabia
20,1021,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
21,1022,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
22,1023,Office Plant,Furniture,2,35.0,2024-06-24,Yes,Germany
23,1024,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan
24,1025,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
25,1026,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
26,1027,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,Argentina
27,1028,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,Russia
28,1029,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
29,1030,Desk Calendar,Furniture,1,18.0,2024-07-01,No,Italy
30,1031,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
31,1032,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
32,1033,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,Colombia
33,1034,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
34,1035,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan
35,1036,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
38,1039,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea
39,1040,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [30]:
df.to_csv("data.csv", index=False)